# Generated by Django 4.1.7 on 2023-03-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_store_app', '0006_alter_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',), 'verbose_name_plural': 'Товары'},
        ),
    ]
