# Generated by Django 4.1.7 on 2023-03-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_store_app', '0008_alter_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name_plural': 'Категории'},
        ),
    ]
