# Generated by Django 4.1.7 on 2023-03-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm_store_app', '0010_alter_category_options_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='Категории', to='orm_store_app.category'),
        ),
    ]
