# Generated by Django 4.1.7 on 2023-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_store_app', '0013_item_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor_code',
            field=models.IntegerField(verbose_name='Артикул'),
        ),
    ]
